version: '3.1'
services:
  casdoor:
    restart: always
    image: houshuai0816/casdoor:latest
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/